### ISSUE TITLE
[BUG] Applying different Conv3d with same stride > 1 on the same tensor leads to different coordinate output

### ISSUE THREAD

**Issue by xuanlinli17** [mit-han-lab/torchsparse#116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I constructed `conv1` and `conv2`, both are `spnn.Conv3d(3,3,kernel_size=3, stride=2)`. I ran `conv1(x)` and `conv2(x)` but got different coordinate outputs. The coordinates from `conv1(x)` is correct, but the coordinates from `conv2(x)` is wrong. 

Might be caused by some deepcopy issues.

```
>>> import torch, torch.nn as nn
>>> import torchsparse.nn.functional as spf
>>> import torchsparse.nn as spnn
>>> from torchsparse import PointTensor, SparseTensor
>>> from torchsparse.nn.utils import get_kernel_offsets
>>> def initial_voxelize(z, init_res, after_res):
...     new_float_coord = torch.cat(
...         [(z.C[:, :3] * init_res) / after_res, z.C[:, -1].view(-1, 1)], 1)
...     pc_hash = spf.sphash(torch.floor(new_float_coord).int())
...     sparse_hash = torch.unique(pc_hash)
...     idx_query = spf.sphashquery(pc_hash, sparse_hash)
...     counts = spf.spcount(idx_query.int(), len(sparse_hash))
...     inserted_coords = spf.spvoxelize(torch.floor(new_float_coord), idx_query,
...                                    counts)
...     inserted_coords = torch.round(inserted_coords).int()
...     inserted_feat = spf.spvoxelize(z.F, idx_query, counts)
...     new_tensor = SparseTensor(inserted_feat, inserted_coords, 1)
...     new_tensor.cmaps.setdefault(new_tensor.stride, new_tensor.coords)
...     z.additional_features['idx_query'][1] = idx_query
...     z.additional_features['counts'][1] = counts
...     z.C = new_float_coord
...     return new_tensor
...
>>> def build_points(xyz, feature):
...     """
...         xyz: [B, N, 3]
...         feature: [B, N, C]
...     """
...     idx = torch.arange(xyz.shape[0], device=xyz.device)[:, None, None].repeat_interleave(xyz.shape[1], 1)
...     xyzb = torch.cat([xyz, idx], dim=-1).reshape(-1, 4).contiguous()
...     feature = feature.reshape(-1, feature.shape[-1]).contiguous()
...     # print(xyzb.shape, feature.shape)
...     return PointTensor(feature, xyzb)
...
>>> xyz = torch.randn(1,10,3)
>>> z = build_points(xyz, xyz)
>>> x = initial_voxelize(z, 1.0, 0.4)
>>> print(x.C)
tensor([[ 3,  0, -4,  0],
        [ 0, -1, -1,  0],
        [-1,  1,  1,  0],
        [-1,  1,  0,  0],
        [ 0,  0,  2,  0],
        [-2, -2, -3,  0],
        [-8,  2,  4,  0],
        [-1,  0,  3,  0],
        [-1,  0,  0,  0],
        [ 0,  5, -2,  0]], dtype=torch.int32)
>>> conv1 = spnn.Conv3d(3,3,kernel_size=3, stride=2)
>>> conv2 = spnn.Conv3d(3,3,kernel_size=3, stride=2)
>>> x1 = conv1(x)
>>> print(x1.C)
tensor([[-8,  2,  4,  0],
        [-2, -2, -4,  0],
        [-2, -2, -2,  0],
        [-2,  0,  0,  0],
        [-2,  0,  2,  0],
        [-2,  0,  4,  0],
        [-2,  2,  0,  0],
        [-2,  2,  2,  0],
        [ 0, -2, -2,  0],
        [ 0, -2,  0,  0],
        [ 0,  0, -2,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  2,  0],
        [ 0,  0,  4,  0],
        [ 0,  2,  0,  0],
        [ 0,  2,  2,  0],
        [ 0,  4, -2,  0],
        [ 0,  6, -2,  0],
        [ 2,  0, -4,  0],
        [ 4,  0, -4,  0]], dtype=torch.int32)
>>> x2 = conv2(x)
>>> print(x2.C)
tensor([[ 3,  0, -4,  0],
        [ 0, -1, -1,  0],
        [-1,  1,  1,  0],
        [-1,  1,  0,  0],
        [ 0,  0,  2,  0],
        [-2, -2, -3,  0],
        [-8,  2,  4,  0],
        [-1,  0,  3,  0],
        [-1,  0,  0,  0],
        [ 0,  5, -2,  0]], dtype=torch.int32)
```

### Expected Behavior

`conv1(x).C` should have the same output as `conv2(x).C`.

### Environment

`torchsparse.__version__ == 1.4.0`

**Comment by xuanlinli17** [comment]
It seems that the coordinates are correct if two Conv3d tensors with same stride > 1 are contained in the same `nn.Module`. However when they are created outside `nn.Module` the same error as above occurs.

**When `net` and `downsample` are inside `nn.Module`:**
```
>>> import torchsparse.nn.functional as spf
>>> import torchsparse.nn as spnn
>>> from torchsparse import PointTensor, SparseTensor
>>> from torchsparse.nn.utils import get_kernel_offsets
>>> def initial_voxelize(z, init_res, after_res):
...     new_float_coord = torch.cat(
...         [(z.C[:, :3] * init_res) / after_res, z.C[:, -1].view(-1, 1)], 1)
...     pc_hash = spf.sphash(torch.floor(new_float_coord).int())
...     sparse_hash = torch.unique(pc_hash)
...     idx_query = spf.sphashquery(pc_hash, sparse_hash)
...     counts = spf.spcount(idx_query.int(), len(sparse_hash))
...     inserted_coords = spf.spvoxelize(torch.floor(new_float_coord), idx_query,
...                                    counts)
...     inserted_coords = torch.round(inserted_coords).int()
...     inserted_feat = spf.spvoxelize(z.F, idx_query, counts)
...     new_tensor = SparseTensor(inserted_feat, inserted_coords, 1)
...     new_tensor.cmaps.setdefault(new_tensor.stride, new_tensor.coords)
...     z.additional_features['idx_query'][1] = idx_query
...     z.additional_features['counts'][1] = counts
...     z.C = new_float_coord
...     return new_tensor
...
>>> def build_points(xyz, feature):
...     """
...         xyz: [B, N, 3]
...         feature: [B, N, C]
...     """
...     idx = torch.arange(xyz.shape[0], device=xyz.device)[:, None, None].repeat_interleave(xyz.shape[1], 1)
...     xyzb = torch.cat([xyz, idx], dim=-1).reshape(-1, 4).contiguous()
...     feature = feature.reshape(-1, feature.shape[-1]).contiguous()
...     # print(xyzb.shape, feature.shape)
...     return PointTensor(feature, xyzb)
...
>>> xyz = torch.randn(1,10,3)
>>> z = build_points(xyz, xyz)
>>> x = initial_voxelize(z, 1.0, 0.4)
>>>
>>> class ResidualBlock(nn.Module):
...     expansion = 1
...     def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, dilation=1):
...         super().__init__()
...         self.net = nn.Sequential(
...             spnn.Conv3d(in_channels,
...                         out_channels,
...                         kernel_size=kernel_size,
...                         dilation=dilation,
...                         stride=stride),
...             spnn.BatchNorm(out_channels),
...             spnn.ReLU(True),
...             spnn.Conv3d(out_channels,
...                         out_channels,
...                         kernel_size=kernel_size,
...                         dilation=dilation,
...                         stride=1),
...             spnn.BatchNorm(out_channels),
...         )
...         if in_channels == out_channels * self.expansion and stride == 1:
...             self.downsample = nn.Sequential()
...         else:
...             if stride == 1:
...                 self.downsample = nn.Sequential(
...                     spnn.Conv3d(in_channels, out_channels, kernel_size=1, dilation=1, stride=stride),
...                     spnn.BatchNorm(out_channels)
...                 )
...             else:
...                 self.downsample = nn.Sequential(
...                     spnn.Conv3d(in_channels, out_channels, kernel_size=3, dilation=1, stride=stride),
...                     spnn.BatchNorm(out_channels)
...                 )
...         self.relu = spnn.ReLU(True)
...     def forward(self, x):
...         return self.relu(self.net(x) + self.downsample(x))
...
>>> r=ResidualBlock(3,3,3,2,1)
>>> x1=r(x)
>>> x1.C
tensor([[-2, -4, -4,  0],
        [-2, -2,  0,  0],
        [-2, -2,  2,  0],
        [-2,  0,  0,  0],
        [-2,  0,  2,  0],
        [-2,  2, -6,  0],
        [-2,  6, -2,  0],
        [-2,  6,  0,  0],
        [-2,  8, -2,  0],
        [-2,  8,  0,  0],
        [ 0, -4, -4,  0],
        [ 0, -2, -4,  0],
        [ 0, -2, -2,  0],
        [ 0,  0, -4,  0],
        [ 0,  0, -2,  0],
        [ 0,  0,  0,  0],
        [ 0,  2, -2,  0],
        [ 0,  2,  0,  0],
        [ 0,  6, -2,  0],
        [ 0,  6,  0,  0],
        [ 0,  8, -2,  0],
        [ 0,  8,  0,  0],
        [ 2, -4, -2,  0],
        [ 2, -2, -2,  0],
        [ 2, -2,  2,  0],
        [ 2,  0, -2,  0],
        [ 2,  0,  0,  0],
        [ 2,  0,  2,  0],
        [ 2,  2, -2,  0],
        [ 2,  2,  0,  0],
        [ 4, -4, -2,  0],
        [ 4, -2, -2,  0],
        [ 4, -2,  0,  0]], dtype=torch.int32)
```





**When `net` and `downsample` are outside of `nn.Module`:**

```
>>> import torchsparse.nn.functional as spf
>>> import torchsparse.nn as spnn
>>> from torchsparse import PointTensor, SparseTensor
>>> from torchsparse.nn.utils import get_kernel_offsets
>>> def initial_voxelize(z, init_res, after_res):
...     new_float_coord = torch.cat(
...         [(z.C[:, :3] * init_res) / after_res, z.C[:, -1].view(-1, 1)], 1)
...     pc_hash = spf.sphash(torch.floor(new_float_coord).int())
...     sparse_hash = torch.unique(pc_hash)
...     idx_query = spf.sphashquery(pc_hash, sparse_hash)
...     counts = spf.spcount(idx_query.int(), len(sparse_hash))
...     inserted_coords = spf.spvoxelize(torch.floor(new_float_coord), idx_query,
...                                    counts)
...     inserted_coords = torch.round(inserted_coords).int()
...     inserted_feat = spf.spvoxelize(z.F, idx_query, counts)
...     new_tensor = SparseTensor(inserted_feat, inserted_coords, 1)
...     new_tensor.cmaps.setdefault(new_tensor.stride, new_tensor.coords)
...     z.additional_features['idx_query'][1] = idx_query
...     z.additional_features['counts'][1] = counts
...     z.C = new_float_coord
...     return new_tensor
...
>>> def build_points(xyz, feature):
...     """
...         xyz: [B, N, 3]
...         feature: [B, N, C]
...     """
...     idx = torch.arange(xyz.shape[0], device=xyz.device)[:, None, None].repeat_interleave(xyz.shape[1], 1)
...     xyzb = torch.cat([xyz, idx], dim=-1).reshape(-1, 4).contiguous()
...     feature = feature.reshape(-1, feature.shape[-1]).contiguous()
...     # print(xyzb.shape, feature.shape)
...     return PointTensor(feature, xyzb)
...
>>> xyz = torch.randn(1,10,3)
>>> z = build_points(xyz, xyz)
>>> x = initial_voxelize(z, 1.0, 0.4)
>>>
>>> in_channel=3
>>> out_channel=3
>>> net = nn.Sequential(
...             spnn.Conv3d(in_channel,
...                         out_channel,
...                         kernel_size=3,
...                         dilation=1,
...                         stride=2),
...             spnn.BatchNorm(out_channel),
...             spnn.ReLU(True),
...             spnn.Conv3d(out_channel,
...                         out_channel,
...                         kernel_size=3,
...                         dilation=1,
...                         stride=2),
...             spnn.BatchNorm(3),
...         )
>>> downsample = nn.Sequential(
...                     spnn.Conv3d(in_channel, out_channel, kernel_size=3, dilation=1, stride=2),
...                     spnn.BatchNorm(out_channel)
...                 )
>>>
>>> net(x) + downsample(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/py38/lib/python3.8/site-packages/torchsparse/tensor.py", line 68, in __add__
    feats=self.feats + other.feats,
RuntimeError: The size of tensor a (12) must match the size of tensor b (26) at non-singleton dimension 0
```

**Comment by zhijian-liu** [comment]
Thanks for reporting the issue! I've submitted a PR to fix this issue. Could you please checkout that branch to see whether it works? Thanks!

**Comment by xuanlinli17** [comment]
Hi zhijian,

When I ran the code in the first thread (replicated here for details), pdb reports `malloc_consolidate(): invalid chunk size` and then seg faults and core dumps. Master version of code is fine.

```
import torch, torch.nn as nn
import torchsparse.nn.functional as spf
import torchsparse.nn as spnn
from torchsparse import PointTensor, SparseTensor
from torchsparse.nn.utils import get_kernel_offsets
def initial_voxelize(z, init_res, after_res):
    new_float_coord = torch.cat(
        [(z.C[:, :3] * init_res) / after_res, z.C[:, -1].view(-1, 1)], 1)
    pc_hash = spf.sphash(torch.floor(new_float_coord).int())
    sparse_hash = torch.unique(pc_hash)
    idx_query = spf.sphashquery(pc_hash, sparse_hash)
    counts = spf.spcount(idx_query.int(), len(sparse_hash))
    inserted_coords = spf.spvoxelize(torch.floor(new_float_coord), idx_query,
                                   counts)
    inserted_coords = torch.round(inserted_coords).int()
    inserted_feat = spf.spvoxelize(z.F, idx_query, counts)
    new_tensor = SparseTensor(inserted_feat, inserted_coords, 1)
    new_tensor.cmaps.setdefault(new_tensor.stride, new_tensor.coords)
    z.additional_features['idx_query'][1] = idx_query
    z.additional_features['counts'][1] = counts
    z.C = new_float_coord
    return new_tensor

def build_points(xyz, feature):
    """
        xyz: [B, N, 3]
        feature: [B, N, C]
    """
    idx = torch.arange(xyz.shape[0], device=xyz.device)[:, None, None].repeat_interleave(xyz.shape[1], 1)
    xyzb = torch.cat([xyz, idx], dim=-1).reshape(-1, 4).contiguous()
    feature = feature.reshape(-1, feature.shape[-1]).contiguous()
    # print(xyzb.shape, feature.shape)
    return PointTensor(feature, xyzb)

xyz = torch.randn(1,10,3)
z = build_points(xyz, xyz)
x = initial_voxelize(z, 1.0, 0.4)

print(x.C)

conv1 = spnn.Conv3d(3,3,kernel_size=3, stride=2)
conv2 = spnn.Conv3d(3,3,kernel_size=3, stride=2)

x1 = conv1(x)
print(x1.C)

x2 = conv2(x)
print(x2.C)
```

Conda env python 3.8 
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             4.5                       1_gnu
ca-certificates           2021.7.5             h06a4308_1
certifi                   2021.5.30        py38h06a4308_0
ld_impl_linux-64          2.35.1               h7274673_9
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.3.0               h5101ec6_17
libgomp                   9.3.0               h5101ec6_17
libstdcxx-ng              9.3.0               hd4cf53a_17
ncurses                   6.2                  he6710b0_1
numpy                     1.21.2                   pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0
pip                       21.0.1           py38h06a4308_0
python                    3.8.11          h12debd9_0_cpython
readline                  8.1                  h27cfd23_0
setuptools                58.0.4           py38h06a4308_0
sqlite                    3.36.0               hc218d9a_0
tk                        8.6.11               h1ccaba5_0
torch                     1.9.1                    pypi_0    pypi
torchsparse               1.4.0                     dev_0    <develop>
typing-extensions         3.10.0.2                 pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3
```

**Comment by zhijian-liu** [comment]
I've pushed a patch to the branch. Could you please try this again and let me know if that works? Thanks!

**Comment by xuanlinli17** [comment]
Seems that it works. Thanks!
