### ISSUE TITLE
importError when running model_zoo

### ISSUE THREAD

**Issue by rgao0313** [mit-han-lab/torchsparse#141]
import torchsparse.backend
ImportError: /home/kelsiegao/anaconda3/envs/torch/lib/python3.7/site-packages/torchsparse/backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jS2_

How to solve this problem?I want to download some pretrained models to test the code. However, the above error happens
python 3.7.11
pytorch 1.7.1

**Comment by zhijian-liu** [comment]
Could you please try re-installing TorchSparse with `pip install -v git+https://github.com/mit-han-lab/torchsparse.git`?

**Comment by rgao0313** [comment]
> Could you please try re-installing TorchSparse with the following command?
> 
> ```
> pip install -v git+https://github.com/mit-han-lab/torchsparse.git
> ```
> 
> Please post the error log if there is any. Thanks!

I reinstall torchsparse as your command. However, it remains the same error as before like the following details














Failed to import tensorflow.
Traceback (most recent call last):
  File "evaluate.py", line 19, in <module>
    from model_zoo import minkunet, spvcnn, spvnas_specialized
  File "/home/kelsiegao/Downloads/spvnas/model_zoo.py", line 9, in <module>
    from core.models.semantic_kitti.minkunet import MinkUNet
  File "/home/kelsiegao/Downloads/spvnas/core/models/semantic_kitti/__init__.py", line 1, in <module>
    from .minkunet import *
  File "/home/kelsiegao/Downloads/spvnas/core/models/semantic_kitti/minkunet.py", line 3, in <module>
    import torchsparse.nn as spnn
  File "/home/kelsiegao/anaconda3/envs/torch/lib/python3.7/site-packages/torchsparse/nn/__init__.py", line 1, in <module>
    from .modules import *
  File "/home/kelsiegao/anaconda3/envs/torch/lib/python3.7/site-packages/torchsparse/nn/modules/__init__.py", line 3, in <module>
    from .conv import *
  File "/home/kelsiegao/anaconda3/envs/torch/lib/python3.7/site-packages/torchsparse/nn/modules/conv.py", line 9, in <module>
    from torchsparse.nn import functional as F
  File "/home/kelsiegao/anaconda3/envs/torch/lib/python3.7/site-packages/torchsparse/nn/functional/__init__.py", line 2, in <module>
    from .conv import *
  File "/home/kelsiegao/anaconda3/envs/torch/lib/python3.7/site-packages/torchsparse/nn/functional/conv.py", line 7, in <module>
    import torchsparse.backend
ImportError: /home/kelsiegao/anaconda3/envs/torch/lib/python3.7/site-packages/torchsparse/backend.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail14torchCheckFailEPKcS2_jS2_

**Comment by zhijian-liu** [comment]
Is there any error or warning from the installation? If so, could you please post them here? Also, you could try to upgrade your PyTorch to the latest version.
