### ISSUE TITLE
[Installation]  Pip install not picking up the default set g++ version 

### ISSUE THREAD

**Issue by sandeepnmenon** [mit-han-lab/torchsparse#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

Install failing saying g++ version is greater than the maximum required by CUDA. Install is not picking the g++ version set using update-alternatives.

### Error Line

      RuntimeError: The current installed version of x86_64-linux-gnu-g++ (11.3.0) is greater than the maximum required version by CUDA 11.3 (10.0.0). Please make sure to use an adequate version of x86_64-linux-gnu-g++ (>=5.0.0, <=10.0.0).

### Environment

```markdown
- GCC: gcc (Ubuntu 10.4.0-4ubuntu1~22.04) 10.4.0
- NVCC: Build cuda_11.3.r11.3/compiler.29745058_0
- PyTorch: 1.12.1+cu113
- PyTorch CUDA: 11.3
```

### Full Error Log

<details>
  <summary>Error Log</summary>

Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-oy8cwpq8/setup.py", line 30, in <module>
          setup(
        File "/home/menonsandu/github/venv-torchsparse/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/menonsandu/github/venv-torchsparse/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/usr/lib/python3.10/distutils/command/install.py", line 619, in run
          self.run_command('build')
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/menonsandu/github/venv-torchsparse/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/usr/lib/python3.10/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/home/menonsandu/github/venv-torchsparse/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 434, in build_extensions
          self._check_cuda_version(compiler_name, compiler_version)
        File "/home/menonsandu/github/venv-torchsparse/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 836, in _check_cuda_version
          raise RuntimeError(
      RuntimeError: The current installed version of x86_64-linux-gnu-g++ (11.3.0) is greater than the maximum required version by CUDA 11.3 (10.0.0). Please make sure to use an adequate version of x86_64-linux-gnu-g++ (>=5.0.0, <=10.0.0).

</details>

**Comment by sandeepnmenon** [comment]
Mitigated by running
```
sudo apt -y install gcc-9 g++-9
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9
export CXX=g++-9
```
Then ran the install command

**Comment by sandeepnmenon** [comment]
After running the above command and running the pip install, it is crashing my system

**Comment by zhijian-liu** [comment]
Since TorchSparse has been upgraded to v2.1.0, could you please attempt to install the latest version? I will now close this issue, but please don't hesitate to reopen it if the problem persists.
