### ISSUE TITLE
[Installation] <title>  ImportError: cannot import name 'PointTensor' from 'torchsparse.tensor' 

### ISSUE THREAD

**Issue by zeliangDing** [mit-han-lab/torchsparse#230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

When I use "https://github.com/zju3dv/NeuralRecon" ,  run " python demo.py --cfg ./config/demo.yaml"
Some trouble happened,like this 

![图片](https://github.com/mit-han-lab/torchsparse/assets/24822200/81b2d0c4-c547-47be-ad8a-9c4e083dd16b)

### Error Line

ImportError: cannot import name 'PointTensor' from 'torchsparse.tensor' 
![10](https://github.com/mit-han-lab/torchsparse/assets/24822200/b100424b-1680-4943-9b45-e82cb3dd6802)

### Environment

```markdown
- GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- NVCC:  Cuda compilation tools, release 11.1, V11.1.105
- PyTorch: 1.9.0
- PyTorch CUDA: 1.9.0+cu111
```

### Full Error Log

<details>
  <summary>Error Log</summary>

  [PUT YOUR ERROR LOG HERE]
</details>

**Comment by zhijian-liu** [comment]
We've removed the definition of `PointTensor` in the latest version. You may refer to https://github.com/mit-han-lab/spvnas/commit/08570cf687622c4d5a5cfa2d7d5f3dcb629222d1 for necessary changes to use the latest TorchSparse. Alternatively, you could also downgrade to v2.0.0.

**Comment by Shadow581** [comment]
But I still have the problem.
torchsparse version: 2.1.0+torch112cu113
![1](https://github.com/mit-han-lab/torchsparse/assets/45356169/0e54b94e-5489-4ce5-986f-6d2a49a3b993)

**Comment by zeliangDing** [comment]
@zhijian-liu @Shadow581  Thanks.  I hope this problem will fixed early!

**Comment by tiancaipipi110** [comment]
> v2.0.0


@zhijian-liu What's the installation guide for 2.0.0? Which cuda and pytorch should one use for python 3.8? `python -c "$(curl -fsSL https://raw.githubusercontent.com/mit-han-lab/torchsparse/master/install.py)" `only installs 2.1.0.

**Comment by zhijian-liu** [comment]
@tiancaipipi110, you could try to install the previous version by
```
pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v2.0.0
```

**Comment by tiancaipipi110** [comment]
@zhijian-liu  Yes, I've tried` pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v2.0.0 `or cloned [here ](https://github.com/mit-han-lab/torchsparse/tree/v2.0.0) `pip install -r requirements.txt` and` python setup.py`  on the following different setups
```
pip install torch==1.12.0+cu113 torchvision==0.13.0+cu113 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu113
conda install pytorch==1.13.0 torchvision==0.14.0 torchaudio==0.13.0 pytorch-cuda=11.6 -c pytorch -c nvidia
conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch
conda install pytorch==1.10.0 torchvision==0.11.0 torchaudio==0.10.0 cudatoolkit=11.3 -c pytorch -c conda-forge
```
and I'm getting either `error: [Errno 2] No such file or directory: ':/usr/local/cuda-11.0/bin/nvcc'` or `error: metadata-generation-failed. 
`


```
/home/vipuser/miniconda3/lib/python3.8/site-packages/setuptools/dist.py:461: UserWarning: Normalizing '2.0.0b' to '2.0.0b0'
  warnings.warn(tmpl.format(**locals()))
running install
running bdist_egg
running egg_info
writing torchsparse.egg-info/PKG-INFO
writing dependency_links to torchsparse.egg-info/dependency_links.txt
writing top-level names to torchsparse.egg-info/top_level.txt
/home/vipuser/miniconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'torchsparse.egg-info/SOURCES.txt'
writing manifest file 'torchsparse.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/lib.linux-x86_64-3.8
creating build/lib.linux-x86_64-3.8/torchsparse
copying torchsparse/version.py -> build/lib.linux-x86_64-3.8/torchsparse
copying torchsparse/__init__.py -> build/lib.linux-x86_64-3.8/torchsparse
copying torchsparse/operators.py -> build/lib.linux-x86_64-3.8/torchsparse
copying torchsparse/tensor.py -> build/lib.linux-x86_64-3.8/torchsparse
copying torchsparse/backends.py -> build/lib.linux-x86_64-3.8/torchsparse
creating build/lib.linux-x86_64-3.8/torchsparse/nn
copying torchsparse/nn/__init__.py -> build/lib.linux-x86_64-3.8/torchsparse/nn
creating build/lib.linux-x86_64-3.8/torchsparse/backbones
copying torchsparse/backbones/resnet.py -> build/lib.linux-x86_64-3.8/torchsparse/backbones
copying torchsparse/backbones/__init__.py -> build/lib.linux-x86_64-3.8/torchsparse/backbones
copying torchsparse/backbones/unet.py -> build/lib.linux-x86_64-3.8/torchsparse/backbones
creating build/lib.linux-x86_64-3.8/torchsparse/utils
copying torchsparse/utils/collate.py -> build/lib.linux-x86_64-3.8/torchsparse/utils
copying torchsparse/utils/__init__.py -> build/lib.linux-x86_64-3.8/torchsparse/utils
copying torchsparse/utils/utils.py -> build/lib.linux-x86_64-3.8/torchsparse/utils
copying torchsparse/utils/tune.py -> build/lib.linux-x86_64-3.8/torchsparse/utils
copying torchsparse/utils/quantize.py -> build/lib.linux-x86_64-3.8/torchsparse/utils
creating build/lib.linux-x86_64-3.8/torchsparse/nn/functional
copying torchsparse/nn/functional/devoxelize.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/functional
copying torchsparse/nn/functional/crop.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/functional
copying torchsparse/nn/functional/conv.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/functional
copying torchsparse/nn/functional/__init__.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/functional
copying torchsparse/nn/functional/pooling.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/functional
copying torchsparse/nn/functional/downsample.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/functional
copying torchsparse/nn/functional/query.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/functional
copying torchsparse/nn/functional/voxelize.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/functional
copying torchsparse/nn/functional/activation.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/functional
copying torchsparse/nn/functional/hash.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/functional
copying torchsparse/nn/functional/count.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/functional
copying torchsparse/nn/functional/build_kmap.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/functional
creating build/lib.linux-x86_64-3.8/torchsparse/nn/utils
copying torchsparse/nn/utils/kernel.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/utils
copying torchsparse/nn/utils/__init__.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/utils
copying torchsparse/nn/utils/apply.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/utils
creating build/lib.linux-x86_64-3.8/torchsparse/nn/modules
copying torchsparse/nn/modules/crop.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/modules
copying torchsparse/nn/modules/conv.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/modules
copying torchsparse/nn/modules/__init__.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/modules
copying torchsparse/nn/modules/pooling.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/modules
copying torchsparse/nn/modules/norm.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/modules
copying torchsparse/nn/modules/activation.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/modules
copying torchsparse/nn/modules/bev.py -> build/lib.linux-x86_64-3.8/torchsparse/nn/modules
creating build/lib.linux-x86_64-3.8/torchsparse/backbones/modules
copying torchsparse/backbones/modules/__init__.py -> build/lib.linux-x86_64-3.8/torchsparse/backbones/modules
copying torchsparse/backbones/modules/blocks.py -> build/lib.linux-x86_64-3.8/torchsparse/backbones/modules
running build_ext
error: [Errno 2] No such file or directory: ':/usr/local/cuda-11.0/bin/nvcc'
```


```
Collecting git+https://github.com/mit-han-lab/torchsparse.git@v2.0.0
  Cloning https://github.com/mit-han-lab/torchsparse.git (to revision v2.0.0) to /tmp/pip-req-build-2n6lj11j
  Running command git clone --filter=blob:none --quiet https://github.com/mit-han-lab/torchsparse.git /tmp/pip-req-build-2n6lj11j
  Running command git checkout -q 1a10fda15098f3bf4fa2d01f8bee53e85762abcf
  Resolved https://github.com/mit-han-lab/torchsparse.git to commit 1a10fda15098f3bf4fa2d01f8bee53e85762abcf
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-2n6lj11j/setup.py", line 4, in <module>
          import torch
        File "/home/vipuser/miniconda3/envs/LeReS/lib/python3.8/site-packages/torch/__init__.py", line 198, in <module>
          _load_global_deps()
        File "/home/vipuser/miniconda3/envs/LeReS/lib/python3.8/site-packages/torch/__init__.py", line 151, in _load_global_deps
          ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
        File "/home/vipuser/miniconda3/envs/LeReS/lib/python3.8/ctypes/__init__.py", line 373, in __init__
          self._handle = _dlopen(self._name, mode)
      OSError: /home/vipuser/miniconda3/envs/LeReS/lib/python3.8/site-packages/torch/lib/libcublas.so.11: symbol cublasLtBIIMatmulAlgoGetHeuristic version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Boyyeo** [comment]
> @tiancaipipi110, you could try to install the previous version by
> 
> ```
> pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v2.0.0
> ```

Hi,  since the way pip install didn't work for me, is it possible to provide the wheel link like (http://pypi.hanlab.ai/simple/torchsparse/) for the version torchsparse (1.4.0 or 2.0.0) ? Thanks for the great works

**Comment by Amber0913** [comment]
@zhijian-liu Could you provide the wheels of v2.0.0？Iencountered an installation error when using this statement `pip install --upgrade git+https://github.com/mit-han-lab/torchsparse.git@v2.0.0`.
