### ISSUE TITLE
build error while installing torchsparse on linux

### ISSUE THREAD

**Issue by sinAshish** [mit-han-lab/torchsparse#30]
I am trying to install torchsparse on linux.
Cuda: 10.2
GPU : Titan Xp.

Any fix to resolve this issue?

**Comment by zhijian-liu** [comment]
Could you share the entire error message with us? Thanks!

**Comment by sinAshish** [comment]
This is error I get while installing torchsparse
```bash
Looking in indexes: http://ftp.daumkakao.com/pypi/simple
Collecting torchsparse
  Downloading http://mirror.kakao.com/pypi/packages/9d/e4/585e274c36b40e646207217f063076a256f90e941adb65b37efca4b13230/torchsparse-0.1.1.tar.gz (1.5 kB)
Building wheels for collected packages: torchsparse
  Building wheel for torchsparse (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/vision/ashish/ashish/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rpxo6s7e/torchsparse_79e72c25da9d4f7b98ab874725003cdf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rpxo6s7e/torchsparse_79e72c25da9d4f7b98ab874725003cdf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-c_fchzgf
       cwd: /tmp/pip-install-rpxo6s7e/torchsparse_79e72c25da9d4f7b98ab874725003cdf/
  Complete output (29 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/torchsparse
  copying torchsparse/__init__.py -> build/lib/torchsparse
  copying torchsparse/cli.py -> build/lib/torchsparse
  installing to build/bdist.linux-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-rpxo6s7e/torchsparse_79e72c25da9d4f7b98ab874725003cdf/setup.py", line 47, in <module>
      'torchsparse = torchsparse.cli:cli',
    File "/home/vision/ashish/ashish/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/vision/ashish/ashish/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/vision/ashish/ashish/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/vision/ashish/ashish/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 335, in run
      self.run_command('install')
    File "/home/vision/ashish/ashish/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/vision/ashish/ashish/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-rpxo6s7e/torchsparse_79e72c25da9d4f7b98ab874725003cdf/setup.py", line 20, in run
      raise Exception("You probably meant to install and run torch-sparse")
  Exception: You probably meant to install and run torch-sparse
  ----------------------------------------
  ERROR: Failed building wheel for torchsparse
  Running setup.py clean for torchsparse
Failed to build torchsparse
Installing collected packages: torchsparse
    Running setup.py install for torchsparse ... error
    ERROR: Command errored out with exit status 1:
     command: /home/vision/ashish/ashish/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rpxo6s7e/torchsparse_79e72c25da9d4f7b98ab874725003cdf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rpxo6s7e/torchsparse_79e72c25da9d4f7b98ab874725003cdf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-pj0ptxbo/install-record.txt --single-version-externally-managed --compile --install-headers /home/vision/ashish/ashish/include/python3.7m/torchsparse
         cwd: /tmp/pip-install-rpxo6s7e/torchsparse_79e72c25da9d4f7b98ab874725003cdf/
    Complete output (14 lines):
    running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rpxo6s7e/torchsparse_79e72c25da9d4f7b98ab874725003cdf/setup.py", line 47, in <module>
        'torchsparse = torchsparse.cli:cli',
      File "/home/vision/ashish/ashish/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/vision/ashish/ashish/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/vision/ashish/ashish/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-rpxo6s7e/torchsparse_79e72c25da9d4f7b98ab874725003cdf/setup.py", line 20, in run
        raise Exception("You probably meant to install and run torch-sparse")
    Exception: You probably meant to install and run torch-sparse
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/vision/ashish/ashish/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rpxo6s7e/torchsparse_79e72c25da9d4f7b98ab874725003cdf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rpxo6s7e/torchsparse_79e72c25da9d4f7b98ab874725003cdf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-pj0ptxbo/install-record.txt --single-version-externally-managed --compile --install-headers /home/vision/ashish/ashish/include/python3.7m/torchsparse Check the logs for full command output.
```

**Comment by sinAshish** [comment]
I tried the previous code of yours from PVCNN for voxelization, and there also I get the foll. error while building the cpp extensions:
```bash
#include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
[12/13] c++ -MMD -MF grouping.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/vision/ashish/ashish/lib/python3.7/site-packages/torch/include -isystem /home/vision/ashish/ashish/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/vision/ashish/ashish/lib/python3.7/site-packages/torch/include/TH -isystem /home/vision/ashish/ashish/lib/python3.7/site-packages/torch/include/THC -isystem /home/vision/tools/cuda-9.0/include -isystem /home/vision/ashish/ashish/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -std=c++17 -c /home/vision/ashish/3D_MTDA/modules/functional/src/grouping/grouping.cpp -o grouping.o 
FAILED: grouping.o 
c++ -MMD -MF grouping.o.d -DTORCH_EXTENSION_NAME=_pvcnn_backend -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/vision/ashish/ashish/lib/python3.7/site-packages/torch/include -isystem /home/vision/ashish/ashish/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/vision/ashish/ashish/lib/python3.7/site-packages/torch/include/TH -isystem /home/vision/ashish/ashish/lib/python3.7/site-packages/torch/include/THC -isystem /home/vision/tools/cuda-9.0/include -isystem /home/vision/ashish/ashish/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -O3 -std=c++17 -c /home/vision/ashish/3D_MTDA/modules/functional/src/grouping/grouping.cpp -o grouping.o 
In file included from /home/vision/ashish/3D_MTDA/modules/functional/src/grouping/../utils.hpp:4:0,
                 from /home/vision/ashish/3D_MTDA/modules/functional/src/grouping/grouping.cpp:4:
/home/vision/ashish/ashish/lib/python3.7/site-packages/torch/include/ATen/cuda/CUDAContext.h:5:10: fatal error: cuda_runtime_api.h: No such file or directory
 #include <cuda_runtime_api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```
This is a small part of the error.
I don't understand why this runs well on colab but not on Titan!

**Comment by zhijian-liu** [comment]
These two errors are actually different:
1. I think you are using `pip install torchsparse`, but please instead follow the instruction at https://github.com/mit-han-lab/torchsparse#installation.
2. The error is because `CUDA_HOME` is not found, which is usually at `/usr/local/cuda/`. Can you double-check whether the header is there?

**Comment by sinAshish** [comment]
thanks, its all ok now
