### ISSUE TITLE
[Installation] Installation in docker 

### ISSUE THREAD

**Issue by maxiuw** [mit-han-lab/torchsparse#335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you followed all the steps in the FAQ?

- [X] I have tried the steps in the FAQ.

### Current Behavior

hi, doesnt seem to be working anymore, i guess due to the fact that pip installation of torchsparse is broken ? any other tips to install it on docker img?

I tired RUN pip3 install git+https://github.com/mit-han-lab/torchsparse.git@v2.1.0 but doesn't see to do the trick

I tired #228 but i doesnt seem to be working 

I also tried to directly run 
`pip install --extra-index-url http://24.199.104.228/simple --trusted-host 24.199.104.228 torchsparse=={__version__}+{torch_tag}{cuda_tag} --force-reinstall` with different versions listed in the file but nothing seems to be working 

### Error Line

ERROR: Could not find a version that satisfies the requirement torchsparse (from versions: none)
ERROR: No matching distribution found for torchsparse

### Environment

```markdown
- GCC: I tried between 9-11.4
- NVCC: 11.8, V11.8.89
- PyTorch: 2.1
- PyTorch CUDA: 1.8
```

### Full Error Log

If I try to do it with  `pip3 install git+https://github.com/mit-han-lab/torchsparse.git@v2.1.0` 
<details>
  <summary>Error Log</summary>
 => ERROR [28/28] RUN pip3 install git+https://github.com/mit-han-lab/torchsparse.git@v2.1.0                                                                                                                          61.9s
------
 > [28/28] RUN pip3 install git+https://github.com/mit-han-lab/torchsparse.git@v2.1.0:
1.913 Collecting git+https://github.com/mit-han-lab/torchsparse.git@v2.1.0
1.914   Cloning https://github.com/mit-han-lab/torchsparse.git (to revision v2.1.0) to /tmp/pip-req-build-8pv6_lef
1.918   Running command git clone --filter=blob:none --quiet https://github.com/mit-han-lab/torchsparse.git /tmp/pip-req-build-8pv6_lef
3.145   Running command git checkout -b v2.1.0 --track origin/v2.1.0
3.592   Switched to a new branch 'v2.1.0'
3.592   Branch 'v2.1.0' set up to track remote branch 'v2.1.0' from 'origin'.
3.595   Resolved https://github.com/mit-han-lab/torchsparse.git to commit e2a6c32ce069ceaf120334f3df102cdb54fdae3f
3.600   Preparing metadata (setup.py): started
9.982   Preparing metadata (setup.py): finished with status 'done'
9.989 Building wheels for collected packages: torchsparse
9.995   Building wheel for torchsparse (setup.py): started
56.78   Building wheel for torchsparse (setup.py): finished with status 'error'
56.81   error: subprocess-exited-with-error
56.81   
56.81   × python setup.py bdist_wheel did not run successfully.
56.81   │ exit code: 1
56.81   ╰─> [126 lines of output]
56.81       No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
56.81       /usr/local/lib/python3.10/dist-packages/setuptools/dist.py:511: UserWarning: Normalizing '2.0.0b' to '2.0.0b0'
56.81         warnings.warn(tmpl.format(**locals()))
56.81       running bdist_wheel
56.81       /usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:502: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
56.81         warnings.warn(msg.format('we could not find ninja.'))
56.81       running build
56.81       running build_py
56.81       creating build
56.81       creating build/lib.linux-x86_64-3.10
56.81       creating build/lib.linux-x86_64-3.10/torchsparse
56.81       copying torchsparse/__init__.py -> build/lib.linux-x86_64-3.10/torchsparse
56.81       copying torchsparse/backends.py -> build/lib.linux-x86_64-3.10/torchsparse
56.81       copying torchsparse/operators.py -> build/lib.linux-x86_64-3.10/torchsparse
56.81       copying torchsparse/tensor.py -> build/lib.linux-x86_64-3.10/torchsparse
56.81       copying torchsparse/version.py -> build/lib.linux-x86_64-3.10/torchsparse
56.81       creating build/lib.linux-x86_64-3.10/torchsparse/backbones
56.81       copying torchsparse/backbones/__init__.py -> build/lib.linux-x86_64-3.10/torchsparse/backbones
56.81       copying torchsparse/backbones/resnet.py -> build/lib.linux-x86_64-3.10/torchsparse/backbones
56.81       copying torchsparse/backbones/unet.py -> build/lib.linux-x86_64-3.10/torchsparse/backbones
56.81       creating build/lib.linux-x86_64-3.10/torchsparse/nn
56.81       copying torchsparse/nn/__init__.py -> build/lib.linux-x86_64-3.10/torchsparse/nn
56.81       creating build/lib.linux-x86_64-3.10/torchsparse/utils
56.81       copying torchsparse/utils/__init__.py -> build/lib.linux-x86_64-3.10/torchsparse/utils
56.81       copying torchsparse/utils/collate.py -> build/lib.linux-x86_64-3.10/torchsparse/utils
56.81       copying torchsparse/utils/quantize.py -> build/lib.linux-x86_64-3.10/torchsparse/utils
56.81       copying torchsparse/utils/tune.py -> build/lib.linux-x86_64-3.10/torchsparse/utils
56.81       copying torchsparse/utils/utils.py -> build/lib.linux-x86_64-3.10/torchsparse/utils
56.81       creating build/lib.linux-x86_64-3.10/torchsparse/backbones/modules
56.81       copying torchsparse/backbones/modules/__init__.py -> build/lib.linux-x86_64-3.10/torchsparse/backbones/modules
56.81       copying torchsparse/backbones/modules/blocks.py -> build/lib.linux-x86_64-3.10/torchsparse/backbones/modules
56.81       creating build/lib.linux-x86_64-3.10/torchsparse/nn/functional
56.81       copying torchsparse/nn/functional/__init__.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/functional
56.81       copying torchsparse/nn/functional/activation.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/functional
56.81       copying torchsparse/nn/functional/build_kmap.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/functional
56.81       copying torchsparse/nn/functional/conv.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/functional
56.81       copying torchsparse/nn/functional/count.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/functional
56.81       copying torchsparse/nn/functional/crop.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/functional
56.81       copying torchsparse/nn/functional/devoxelize.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/functional
56.81       copying torchsparse/nn/functional/downsample.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/functional
56.81       copying torchsparse/nn/functional/hash.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/functional
56.81       copying torchsparse/nn/functional/pooling.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/functional
56.81       copying torchsparse/nn/functional/query.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/functional
56.81       copying torchsparse/nn/functional/voxelize.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/functional
56.81       creating build/lib.linux-x86_64-3.10/torchsparse/nn/modules
56.81       copying torchsparse/nn/modules/__init__.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/modules
56.81       copying torchsparse/nn/modules/activation.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/modules
56.81       copying torchsparse/nn/modules/bev.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/modules
56.81       copying torchsparse/nn/modules/conv.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/modules
56.81       copying torchsparse/nn/modules/crop.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/modules
56.81       copying torchsparse/nn/modules/norm.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/modules
56.81       copying torchsparse/nn/modules/pooling.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/modules
56.81       creating build/lib.linux-x86_64-3.10/torchsparse/nn/utils
56.81       copying torchsparse/nn/utils/__init__.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/utils
56.81       copying torchsparse/nn/utils/apply.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/utils
56.81       copying torchsparse/nn/utils/kernel.py -> build/lib.linux-x86_64-3.10/torchsparse/nn/utils
56.81       running build_ext
56.81       /usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 11.8
56.81         warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
56.81       building 'torchsparse.backend' extension
56.81       creating build/temp.linux-x86_64-3.10
56.81       creating build/temp.linux-x86_64-3.10/torchsparse
56.81       creating build/temp.linux-x86_64-3.10/torchsparse/backend
56.81       creating build/temp.linux-x86_64-3.10/torchsparse/backend/convolution
56.81       creating build/temp.linux-x86_64-3.10/torchsparse/backend/devoxelize
56.81       creating build/temp.linux-x86_64-3.10/torchsparse/backend/hash
56.81       creating build/temp.linux-x86_64-3.10/torchsparse/backend/hashmap
56.81       creating build/temp.linux-x86_64-3.10/torchsparse/backend/others
56.81       creating build/temp.linux-x86_64-3.10/torchsparse/backend/voxelize
56.81       x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.10/dist-packages/torch/include -I/usr/local/lib/python3.10/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.10/dist-packages/torch/include/TH -I/usr/local/lib/python3.10/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.10 -c torchsparse/backend/convolution/convolution_cpu.cpp -o build/temp.linux-x86_64-3.10/torchsparse/backend/convolution/convolution_cpu.o -g -O3 -fopenmp -lgomp -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=backend -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
56.81       Traceback (most recent call last):
56.81         File "<string>", line 2, in <module>
56.81         File "<pip-setuptools-caller>", line 34, in <module>
56.81         File "/tmp/pip-req-build-8pv6_lef/setup.py", line 30, in <module>
56.81           setup(
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 79, in setup
56.81           return distutils.core.setup(**attrs)
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 148, in setup
56.81           return run_commands(dist)
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
56.81           dist.run_commands()
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
56.81           self.run_command(cmd)
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1196, in run_command
56.81           super().run_command(command)
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
56.81           cmd_obj.run()
56.81         File "/usr/local/lib/python3.10/dist-packages/wheel/bdist_wheel.py", line 368, in run
56.81           self.run_command("build")
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
56.81           self.distribution.run_command(command)
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1196, in run_command
56.81           super().run_command(command)
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
56.81           cmd_obj.run()
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build.py", line 135, in run
56.81           self.run_command(cmd_name)
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
56.81           self.distribution.run_command(command)
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1196, in run_command
56.81           super().run_command(command)
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
56.81           cmd_obj.run()
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/command/build_ext.py", line 79, in run
56.81           _build_ext.run(self)
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
56.81           self.build_extensions()
56.81         File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 873, in build_extensions
56.81           build_ext.build_extensions(self)
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
56.81           self._build_extensions_serial()
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
56.81           self.build_extension(ext)
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/command/build_ext.py", line 202, in build_extension
56.81           _build_ext.build_extension(self, ext)
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
56.81           objects = self.compiler.compile(sources,
56.81         File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/ccompiler.py", line 574, in compile
56.81           self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
56.81         File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 609, in unix_wrap_single_compile
56.81           cflags = unix_cuda_flags(cflags)
56.81         File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 576, in unix_cuda_flags
56.81           cflags + _get_cuda_arch_flags(cflags))
56.81         File "/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py", line 1980, in _get_cuda_arch_flags
56.81           arch_list[-1] += '+PTX'
56.81       IndexError: list index out of range
56.81       [end of output]
56.81   
56.81   note: This error originates from a subprocess, and is likely not a problem with pip.
56.81   ERROR: Failed building wheel for torchsparse
56.81   Running setup.py clean for torchsparse
61.64 Failed to build torchsparse
61.64 ERROR: Could not build wheels for torchsparse, which is required to install pyproject.toml-based projects
61.64 
61.64 [notice] A new release of pip is available: 23.3.1 -> 24.2
61.64 [notice] To update, run: python3.10 -m pip install --upgrade pip
</details>

**Comment by jianchaoci** [comment]
Have you solve the problem? I got same problem with similar configuration
