### ISSUE TITLE
RuntimeError @"return hash_gpu(idx)" in torchsparse/nn/functional/hash.py

### ISSUE THREAD

**Issue by Timingan** [mit-han-lab/torchsparse#36]
Hi,

Thanks for the impressive work. When I try to run the following command on my Pascal machine, I am getting an error.
**Command:**
`torchpack dist-run -np 1 python evaluate.py configs/semantic_kitti/default.yaml --name SemanticKITTI_val_SPVNAS@65GMACs`

**Error:**
```
Traceback (most recent call last):
  File "evaluate.py", line 148, in <module>
    main()
  File "evaluate.py", line 66, in main
    model = spvnas_specialized(args.name)
  File "/root/hostCurUser/e3d/spvnas/model_zoo.py", line 50, in spvnas_specialized
    model = model.determinize()
  File "/root/hostCurUser/e3d/spvnas/core/models/semantic_kitti/spvnas.py", line 311, in determinize
    x = self.forward(x)
  File "/root/hostCurUser/e3d/spvnas/core/models/semantic_kitti/spvnas.py", line 329, in forward
    x0 = point_to_voxel(x, z)
  File "/root/hostCurUser/e3d/spvnas/core/models/utils.py", line 49, in point_to_voxel
    sparse_hash = spf.sphash(x.C)
  File "/root/miniconda3/envs/3D-prj/lib/python3.8/site-packages/torchsparse-1.1.0-py3.8-linux-x86_64.egg/torchsparse/nn/functional/hash.py", line 45, in sphash
    return hash_gpu(idx)
  File "/root/miniconda3/envs/3D-prj/lib/python3.8/site-packages/torchsparse-1.1.0-py3.8-linux-x86_64.egg/torchsparse/nn/functional/hash.py", line 12, in forward
    print(idx.contiguous())
  File "/root/miniconda3/envs/3D-prj/lib/python3.8/site-packages/torch/tensor.py", line 179, in __repr__
    return torch._tensor_str._str(self)
  File "/root/miniconda3/envs/3D-prj/lib/python3.8/site-packages/torch/_tensor_str.py", line 374, in _str
    return _str_intern(self)
  File "/root/miniconda3/envs/3D-prj/lib/python3.8/site-packages/torch/_tensor_str.py", line 354, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/root/miniconda3/envs/3D-prj/lib/python3.8/site-packages/torch/_tensor_str.py", line 241, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/root/miniconda3/envs/3D-prj/lib/python3.8/site-packages/torch/_tensor_str.py", line 274, in get_summarized_data
    print(torch.stack([get_summarized_data(x) for x in (start + end)]))
RuntimeError: CUDA error: invalid device function
Segmentation fault (core dumped)
```

When I installed the torchsparse package, I also got the same error as mit-han-lab/e3d#23. I run the following codes as showed in the pervious issue mit-han-lab/e3d#23. 

```
export FORCE_CUDA="1"
export TORCH_CUDA_ARCH_LIST=“Pascal”
```

Environment details:
python 3.8
pytorch 1.7.1
Cuda 10.1
miniconda3
GPU TITAN Xp

Could you help with the problem? Thanks!

**Comment by zhijian-liu** [comment]
@sandeepnmenon, I saw you have encountered similar issues before. Would you be able to help @Timingan with the issue? Thanks!

**Comment by zhijian-liu** [comment]
I'm closing this issue due to inactivity. Please feel free to reopen it if the problem has not been resolved.
