### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by ptzu** [mit-han-lab/torchsparse#44]
Hi, I followed the instructions in README 
`torchpack dist-run -np 1 python evaluate.py configs/semantic_kitti/default.yaml --name SemanticKITTI_val_SPVNAS@65GMACs`
I wonder if there is any step I missed. There are some error messages:
```
Downloading: "https://hanlab.mit.edu/files/SPVNAS/spvnas_specialized/SemanticKITTI_val_SPVNAS@65GMACs/net.config" to .torch/spvnas_specialized/SemanticKITTI_val_SPVNAS@65GMACs/net.config
Traceback (most recent call last):
  File "evaluate.py", line 146, in <module>
    main()
  File "evaluate.py", line 65, in main
    model = spvnas_specialized(args.name)
  File "/home/roger/workspace/e3d/spvnas/model_zoo.py", line 50, in spvnas_specialized
    model = model.determinize()
  File "/home/roger/workspace/e3d/spvnas/core/models/semantic_kitti/spvnas.py", line 311, in determinize
    x = self.forward(x)
  File "/home/roger/workspace/e3d/spvnas/core/models/semantic_kitti/spvnas.py", line 331, in forward
    x0 = self.stem(x0)
  File "/home/roger/anaconda3/envs/e3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/roger/anaconda3/envs/e3d/lib/python3.6/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/roger/anaconda3/envs/e3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/roger/anaconda3/envs/e3d/lib/python3.6/site-packages/torchsparse/nn/modules/conv.py", line 78, in forward
    transpose=self.t)
  File "/home/roger/anaconda3/envs/e3d/lib/python3.6/site-packages/torchsparse/nn/functional/conv.py", line 151, in conv3d
    idx_query[1], sizes, transpose)
  File "/home/roger/anaconda3/envs/e3d/lib/python3.6/site-packages/torchsparse/nn/functional/conv.py", line 40, in forward
    transpose)
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling cublasCreate(handle)
```
I ran it on Anaconda environment, and my environment information is as follow:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
absl-py                   0.12.0                   pypi_0    pypi
aiocontextvars            0.2.2                    pypi_0    pypi
ca-certificates           2021.1.19            h06a4308_1  
cached-property           1.5.2                    pypi_0    pypi
cachetools                4.2.1                    pypi_0    pypi
certifi                   2020.12.5        py36h06a4308_0  
chardet                   4.0.0                    pypi_0    pypi
contextvars               2.4                      pypi_0    pypi
cudatoolkit               10.2.89              hfd86e86_1  
dataclasses               0.8                      pypi_0    pypi
google-auth               1.28.0                   pypi_0    pypi
google-auth-oauthlib      0.4.3                    pypi_0    pypi
grpcio                    1.36.1                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
immutables                0.15                     pypi_0    pypi
importlib-metadata        3.7.3                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
llvmlite                  0.36.0                   pypi_0    pypi
loguru                    0.5.3                    pypi_0    pypi
markdown                  3.3.4                    pypi_0    pypi
mpi4py                    3.0.3                    pypi_0    pypi
msgpack                   1.0.2                    pypi_0    pypi
msgpack-numpy             0.4.7.1                  pypi_0    pypi
multimethod               1.5                      pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
numba                     0.53.0                   pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
opencv-python             4.5.1.48                 pypi_0    pypi
openssl                   1.1.1j               h27cfd23_0  
pillow                    8.1.2                    pypi_0    pypi
pip                       21.0.1           py36h06a4308_0  
protobuf                  3.15.6                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
python                    3.6.13               hdb3f193_0  
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.0.3                   pypi_0    pypi
readline                  8.1                  h27cfd23_0  
requests                  2.25.1                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
setuptools                52.0.0           py36h06a4308_0  
six                       1.15.0                   pypi_0    pypi
sqlite                    3.35.1               hdfb4753_0  
tabulate                  0.8.9                    pypi_0    pypi
tdqm                      0.0.1                    pypi_0    pypi
tensorboard               2.4.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorboardx              2.1                      pypi_0    pypi
tensorpack                0.11                     pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
torch                     1.8.0                    pypi_0    pypi
torchaudio                0.8.0                    pypi_0    pypi
torchpack                 0.3.0                    pypi_0    pypi
torchsparse               1.1.0                    pypi_0    pypi
torchvision               0.9.0                    pypi_0    pypi
tqdm                      4.59.0                   pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.4                   pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zipp                      3.4.1                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3 
```
Thank you!

**Comment by zhijian-liu** [comment]
It's hard to tell the reason directly from the error message. Could you rerun the code with `CUDA_LAUNCH_BLOCKING=1  torchpack ...`?

**Comment by ptzu** [comment]
`CUDA_LAUNCH_BLOCKING=1 torchpack dist-run -np 1 python evaluate.py configs/semantic_kitti/default.yaml --name SemanticKITTI_val_SPVNAS@65GMACs`
```
No protocol specified
Failed to import tensorflow.
[2021-03-19 16:23:02.575] /home/roger/anaconda3/envs/e3d/bin/python evaluate.py configs/semantic_kitti/default.yaml --name SemanticKITTI_val_SPVNAS@65GMACs
[2021-03-19 16:23:02.575] Experiment started: "runs/run-d58b1287-351d974b".
workers_per_gpu: 8
data:
  num_classes: 19
  ignore_label: 255
  training_size: 19132
train:
  seed: 1588147245
  deterministic: False
dataset:
  name: semantic_kitti
  root: dataset/semantic-kitti
  num_points: 80000
  voxel_size: 0.05
num_epochs: 15
batch_size: 2
criterion:
  name: cross_entropy
  ignore_index: 255
optimizer:
  name: sgd
  lr: 0.24
  weight_decay: 0.0001
  momentum: 0.9
  nesterov: True
scheduler:
  name: cosine_warmup
Traceback (most recent call last):
  File "evaluate.py", line 146, in <module>
    main()
  File "evaluate.py", line 65, in main
    model = spvnas_specialized(args.name)
  File "/home/roger/workspace/e3d/spvnas/model_zoo.py", line 50, in spvnas_specialized
    model = model.determinize()
  File "/home/roger/workspace/e3d/spvnas/core/models/semantic_kitti/spvnas.py", line 311, in determinize
    x = self.forward(x)
  File "/home/roger/workspace/e3d/spvnas/core/models/semantic_kitti/spvnas.py", line 331, in forward
    x0 = self.stem(x0)
  File "/home/roger/anaconda3/envs/e3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/roger/anaconda3/envs/e3d/lib/python3.6/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/roger/anaconda3/envs/e3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/roger/anaconda3/envs/e3d/lib/python3.6/site-packages/torchsparse/nn/modules/conv.py", line 78, in forward
    transpose=self.t)
  File "/home/roger/anaconda3/envs/e3d/lib/python3.6/site-packages/torchsparse/nn/functional/conv.py", line 151, in conv3d
    idx_query[1], sizes, transpose)
  File "/home/roger/anaconda3/envs/e3d/lib/python3.6/site-packages/torchsparse/nn/functional/conv.py", line 40, in forward
    transpose)
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[38437,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by zhijian-liu** [comment]
I'm not sure whether it's related to the PyTorch version. Could you try to use 1.6.0?

**Comment by zhijian-liu** [comment]
This seems related: https://discuss.pytorch.org/t/cuda-error-cublas-status-internal-error-when-calling-cublascreate-handle/114341.

**Comment by zhijian-liu** [comment]
Could you also try whether the following code reproduces the error?
```
import torch

if __name__ == "__main__":
    DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    m = torch.nn.Linear(20, 30).to(DEVICE)
    input = torch.randn(128, 20).to(DEVICE)
    output = m(input)
    print('output', output.size())
```
If so, you can downgrade the PyTorch version to 1.7.1 to see whether that resolves the issue.

**Comment by zhijian-liu** [comment]
I'm closing this issue due to inactivity. Please feel free to reopen it if the problem has not been resolved.
