### ISSUE TITLE
Runtime error and CUDA version

### ISSUE THREAD

**Issue by FrancescoMandru** [mit-han-lab/torchsparse#58]
If I copy and paste your `example.py` I get the following error:

```
root@cb8599ff5efb:/working_dir# python -m sparseUnet.example_test
Starting dummy training...
<torchsparse.sparse_tensor.SparseTensor object at 0x7f27fab94e80>
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/working_dir/sparseUnet/example_test.py", line 71, in <module>
    dummy_train(device)
  File "/working_dir/sparseUnet/example_test.py", line 63, in dummy_train
    loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError
```

I'm running this in CPU mode inside my Docker container with the specifications provided, I have provided to you my Dockerfile in the attachment

[Dockerfile.zip](https://github.com/mit-han-lab/torchsparse/files/6286422/Dockerfile.zip)

Also, running the `performance.py` I get another error:

```
root@04efb3781b40:/working_dir# python -m sparseUnet.example_test2
DEVICE:  cpu
Starting dummy_train_3x1 ...
[W record_function.cpp:154] Exception in RecordFunction callback: /pytorch/torch/csrc/autograd/profiler_cuda.cpp:36: CUDA driver version is insufficient for CUDA runtime version , for the range profiler::_record_function_enter
[W record_function.cpp:154] Exception in RecordFunction callback: /pytorch/torch/csrc/autograd/profiler_cuda.cpp:36: CUDA driver version is insufficient for CUDA runtime version , for the range profiler::_record_function_enter
[W record_function.cpp:154] Exception in RecordFunction callback: /pytorch/torch/csrc/autograd/profiler_cuda.cpp:36: CUDA driver version is insufficient for CUDA runtime version , for the range model_inference
[W record_function.cpp:154] Exception in RecordFunction callback: /pytorch/torch/csrc/autograd/profiler_cuda.cpp:36: CUDA driver version is insufficient for CUDA runtime version , for the range model_inference
Traceback (most recent call last):
  File "/working_dir/sparseUnet/example_test2.py", line 97, in dummy_train_3x1
    with profiler.record_function("model_inference"):
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/profiler.py", line 419, in __enter__
    self.handle = torch.ops.profiler._record_function_enter(self.name)
RuntimeError: /pytorch/torch/csrc/autograd/profiler_cuda.cpp:36: CUDA driver version is insufficient for CUDA runtime version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/working_dir/sparseUnet/example_test2.py", line 119, in <module>
    dummy_train_3x1(device)
  File "/working_dir/sparseUnet/example_test2.py", line 106, in dummy_train_3x1
    optimizer.step()
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/profiler.py", line 326, in __exit__
    records = torch.autograd._disable_profiler()
RuntimeError: /pytorch/torch/csrc/autograd/profiler_cuda.cpp:36: CUDA driver version is insufficient for CUDA runtime version
```

I have already changed to cuda 10.2 but the error remains. I am on Mac OS but Inside Docker

**Comment by zhijian-liu** [comment]
Just to clarify, are you using CPU or GPU for training? From the output log, it seems that the device is CPU. If so, we do not support training with CPU right now.

**Comment by FrancescoMandru** [comment]
Hi @zhijian-liu  thanks for your reply, yes I was testing it with CPU, is it related with torchsparse modules right? 

Anyway, I opened a google colab to test the other work you have done (SPVNAS) and I opened a related issue there.

**Comment by zhijian-liu** [comment]
That's right. TorchSparse only supports the inference but not the training in CPU mode.
