### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Nekomiya-fubuki** [mit-han-lab/torchsparse#80]
Hello,I want to ask a question.I install torchsparse for a code.When I run the code,an erro occurred here.Could you tell me how can I sovle it?

Traceback (most recent call last):
File "demo.py", line 76, in
outputs, loss_dict = model(sample, save_scene)
File "/home/u/anaconda3/envs/neucon/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
result = self.forward(*input, **kwargs)
File "/home/u/anaconda3/envs/neucon/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
return self.module(*inputs[0], **kwargs[0])
File "/home/u/anaconda3/envs/neucon/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
result = self.forward(*input, **kwargs)
File "/home/u/Documents/NeuralRecon-master/models/neuralrecon.py", line 82, in forward
outputs, loss_dict = self.neucon_net(features, inputs, outputs)
File "/home/u/anaconda3/envs/neucon/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
result = self.forward(*input, **kwargs)
File "/home/u/Documents/NeuralRecon-master/models/neucon_network.py", line 157, in forward
feat = self.sp_convsi
File "/home/u/anaconda3/envs/neucon/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
result = self.forward(*input, **kwargs)
File "/home/u/Documents/NeuralRecon-master/models/modules.py", line 147, in forward
x0 = initial_voxelize(z, self.pres, self.vres)
File "/home/u/Documents/NeuralRecon-master/ops/torchsparse_utils.py", line 19, in initial_voxelize
pc_hash = spf.sphash(torch.floor(new_float_coord).int())
File "/home/u/anaconda3/envs/neucon/lib/python3.7/site-packages/torchsparse/nn/functional/hash.py", line 39, in sphash
return HashGPU.apply(idx)
File "/home/u/anaconda3/envs/neucon/lib/python3.7/site-packages/torchsparse/nn/functional/hash.py", line 11, in forward
return torchsparse_backend.hash_forward(idx.contiguous())
AttributeError: module 'torchsparse_backend' has no attribute 'hash_forward'

Is this casused by a mismatch between the torch version and the torchsparse version?
My pytorch version == 1.6.0;torchvision == 0.7.0

**Comment by zhijian-liu** [comment]
Could you please try the latest release version? Thanks!

**Comment by LeonardoCBoar** [comment]
Hi!
I'm also with this problem using version 1.2.0. But when i update to version 1.4.0, this error appears: 
"No module named 'torch sparse.point tensor'"

Is there any solution?

**Comment by zhijian-liu** [comment]
You need to change `from torchsparse.point_tensor import PointTensor` to `from torchsparse import PointTensor`.

**Comment by LeonardoCBoar** [comment]
Thank you!
That worked.
Now i found this one:
```
from torchsparse.utils.kernel_region import *
ModuleNotFoundError: No module named 'torchsparse.utils.kernel_region' 
```

**Comment by zhijian-liu** [comment]
See https://github.com/mit-han-lab/torchsparse/releases/tag/v1.4.0 for these API changes.

**Comment by LeonardoCBoar** [comment]
Thanks! I'll take a look at there
