### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by humanpose1** [mit-han-lab/torchsparse#83]
there is a bug in torchsparse when I execute the following command:
```
python examples/example.py
```

I get the following error
```
Starting dummy training...
Traceback (most recent call last):
  File "examples/example.py", line 82, in <module>
    dummy_train(device, args.mixed)
  File "examples/example.py", line 63, in dummy_train
    outputs = model(inputs)
  File /lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/lib/python3.8/site-packages/torchsparse/nn/modules/conv.py", line 82, in forward
    return spF.conv3d(inputs,
  File "/lib/python3.8/site-packages/torchsparse/nn/functional/conv.py", line 132, in conv3d
    new_coords = spF.spdownsample(coords, stride, kernel_size,
  File "/lib/python3.8/site-packages/torchsparse/nn/functional/downsample.py", line 40, in spdownsample
    kernel_region = KernelRegion(kernel_size, tensor_stride, dilation=1)
  File "/lib/python3.8/site-packages/torchsparse/utils/kernel.py", line 23, in __init__
    assert len(self.tensor_stride) == 3, 'Wrong tensor_stride'
TypeError: object of type 'NoneType' has no len()

```

**Comment by CCInc** [comment]
Hi @humanpose1 , I'm not getting this error on torch 1.6 and 1.7. Can you share more about your environment and whether you're using cpu or gpu? (`torch.cuda.is_available()`)

**Comment by humanpose1** [comment]
I have torch version of 1.8.1+cu102. The problem comes from `torchsparse` . I think it is because I installed the new version of torchsparse. Now The problem with `make_tuple` is solved., the example code works but the function `downsample` is not working.

**Comment by humanpose1** [comment]
In this [line](https://github.com/mit-han-lab/torchsparse/blob/ab1faa0218314c814d26e38bd8baa858aa0ecce2/torchsparse/nn/functional/downsample.py#L64)Why  do you perform :
```
new_coords = new_coords[(new_coords[:, 1] >= 0)
                                & (new_coords[:, 2] >= 0) &
                                (new_coords[:, 3] >= 0)]
```
? 
The coordinates cannot be negative ?

**Comment by zhijian-liu** [comment]
This is fixed in the latest release. Thanks!
